name: metabase
type: java:8
disk: 2048

relationships:
    metabasedb: "metabasedb:postgresql"

mounts:
    temp:
        source: local
        source_path: temp
    data:
        source: local
        source_path: data

web:
  commands:
    start: "sh ./start.sh"
